#!/usr/bin/env python
#ref https://github.com/boto/boto/blob/develop/docs/source/s3_tut.rst
import boto
from boto.s3.connection import S3Connection
from boto.s3.key import Key
import getopt, sys

def usage():
    print """useage: s3cp -b <bucket> -k <key> -d <dstbucket> -t <dstkey>"""

#ref https://github.com/boto/boto/blob/develop/boto/s3/key.py#L413
def s3cp(s3,bucket,key,dstbucket,dstkey):
    b = s3.get_bucket(bucket) 
    k = Key(b)
    k.key = key
    k.copy(dstbucket,dstkey)

if __name__ == "__main__":
    try:
        opts, args = getopt.getopt(sys.argv[1:], "b:k:d:t:",['bucket=','key=','dstbucket=',"dstkey="] )
    except getopt.GetoptError as err:
        usage()
        sys.exit(2)

    bucket=None
    key=None
    dstbucket=None
    dstkey=None
    for o, a in opts:
        if o in ("-b", "--bucekt"):
            bucket = a
        elif o in ("-k", "--key"):
            key = a
        elif o in ("-d", "--dstbucket"):
            dstbucket = a
        elif o in ("-t", "--dstkey"):
            dstkey = a
        else:
            print "error option : [%s]" ,o
            usage()
            sys.exit(2)
    if bucket and key and dstbucket and dstkey:
        s3=boto.connect_s3()
        s3cp(s3,bucket,key,dstbucket,dstkey)
    usage()
    sys.exit(0)

