#!/usr/bin/env python
#ref https://github.com/boto/boto/blob/develop/docs/source/s3_tut.rst
import boto
from boto.s3.connection import S3Connection
import getopt, sys

def s3set(s3,bucket,key,value):
    from boto.s3.key import Key
    b = s3.get_bucket(bucket) 
    k = Key(b)
    k.key = key
    k.set_contents_from_string(value) 

def usage():
    print "useage:"
    pass
if __name__ == "__main__":
    try:
        opts, args = getopt.getopt(sys.argv[1:], "b:k:v:f:",['bucket=','key=','value=','file='] )
    except getopt.GetoptError as err:
        print "GetoptErro"
        usage()
        sys.exit(2)
    for o, a in opts:
        if o in ("-b", "--bucekt"):
            bucket = a
        elif o in ("-k", "--key"):
            key = a
        elif o in ("-v", "--value"):
            value = a
        elif o in ("-f", "--file"):
            files = a
        else:
            print "error option : [%s]" ,o
            usage()
            sys.exit(2)
    
    s3=boto.connect_s3(calling_format = boto.s3.connection.OrdinaryCallingFormat(),)
    s3set(s3,bucket,key,value)
